### ISSUE TITLE
Beta testing

### ISSUE THREAD

**Issue by jeroenpardon** [jeroenpardon/skin.grid.beta#1]
Hi,

Please share some info about yourself here. Some examples:

- Why do you want to test Grid?
- What do you use Kodi for mostly?
- What do you look for in a Kodi skin?
- What would you be able to contribute to best?
- Any special expertise you think is good to know
- Etc..

Just tell me what you think is good to know about you and why or how you would be able to contribute. There's no good or wrong here, I will be looking for people with different backgrounds. motivations, contributions.

**Comment by Donderstraal** [comment]
- Why do you want to test Grid?
There's way to few good Kodi skins out there, I'm very picky with my setup.

- What do you use Kodi for mostly?
It's a PVR STB replacement first, about 80% PVR but not much else really.

- What do you look for in a Kodi skin?
Good navigation... it's something that's hard to find in a skin. Good homescreen. Not too many logo's etc, clean but modern look. Also MCE blue is really nice as it not only gives nice contrast for the eye but also works great for both white and black tv logo's... there's way too many black and dark skins out there...

- What would you be able to contribute to best?
The PVR part, simple code fixes, my opinion on how something should look or feel.

- Any special expertise you think is good to know
I've done fixes for other skins for the PVR part before... on top of that I maintain a Dutch and Western-European logo pack. Always wanted to make my own skin just don't have the time to do it from scratch.

**Comment by loggio** [comment]
Hi Jeroen,

I've been a user and advocate for XBMP/XBMC/Kodi since its inception back in the XBOX days, so I know Kodi like the back of my hand and I'm very quick to notice when something isn't working as it should.

The skin?
I'm all for ease of use, simplicity and functionality but having said that, it's gotta look good too! 
basically I'm with Donderstraal on this one... I'm very picky. There's a lot of skins out there but only 3 that I can think of that I'd even consider using as a main skin... and trust me, I've tried them all.

I've become familiar with the skinning structure and code base as I've been modifying skins... So I may even be able to help out in that regard. 

Right now I use my personal modified version of Jurialmunkey's Arctic Zephyr skin. This skin is great out of the box but I've made many improvements mainly with how the user would expect to interact with the ui on a couch with a remote in hand without having to deviate from or ruin the integrity of the original design.  If you're interested to see some of things I've change I'd be happy to send you some screenshots.

Although I don't use Refocus these days, I loved your Focus skin back in the day.. It was my go to skin! so I'm familiar with your skinning ability and because of this I'd be more than happy to help out with your new project.

•What do you use Kodi for mostly?
1. I have 4 kodi devices in the house. 2 RPi's and 2 Intel PC's. I use Kodi as my PVR with TVheadend running free to air tv on a dedicated RPi backend, so I'm right across the Live TV side of things. This is one thing I'm incredibly picky with so i'll definitely help you get it 100%
2. EVERYTHING! It's my movies hub, it's my tv show hub, it's my music hub. It's my one stop shop, so i guess I'm incredibly picky when it comes to view types and their functionality.

However, I will say that other than having a github account... I'm certainly not familiar with how to use it but that's simply because I've never had to. I'm sure it won't take me long to figure it out... If there's anything to figure out lol.

Anyways, at the risk of going off on too many tangents i'll wind it up here. If you decide to decline me I'm fine with that... no pressure! and all the best with your skin.

**Comment by bigdaddyral** [comment]
Why do you want to test Grid?
Of all the XBMC skins over the years, I've never found a better skin than ReFocus. I'm a big fan of your work and would love to help give back for everything your skin has given me.

What do you use Kodi for mostly?
I watch Movies and TV shows primarily from the Blu-Ray/DVD collection on my NAS.

What do you look for in a Kodi skin?
UI and UX congruity, ease of use, and attractiveness.

What would you be able to contribute to best?
I've worked in IT all my life, but spent a year as a game tester for Mindscape so I'm very familiar with the bug finding and reporting process and fix testing.

Any special expertise you think is good to know
I've done my fair share of web and graphic design over the years and have an eye for good design as well as a superb attention to detail and troubleshooting. I'm also a film maker and home theater enthusiast. I live full time in an Airstream travel trailer and am self employed. My setup is a single Intel NUC running Ubuntu connected to a Synology NAS that feeds both TVs in the trailer. Though I live on the road, I need my HTPC with me. :)

**Comment by purpleman2k** [comment]
**Why do you want to test Grid?**
I've been following Refocus and your work in the past 5 years. It is my only skin of choice, and I could not find any other design that I liked. 
I'm a programmer myself, and made my own adjustments to multiple versions over the years. Sometimes just to add support for a new beta version of Kodi (I'm an early adopter) and sometimes to make small nitpicking changes. In any case, I'm a huge fan of your sense of aesthetics and I'm excited about a change to a new skin.

**What do you use Kodi for mostly?**
Kodi runs on my living room HTPC. It's used for Movies, TV Shows, Music, Pictures and Live TV (DVR).

**What do you look for in a Kodi skin?**
Elegance, aesthetics and the lack of an over-the-top design (which is what most skin suffer from in my opinion). Sometimes less is more, and being easy on the eyes and having a makes-sense UI is more important than anything else. 

**What would you be able to contribute to best?**
Bug reports, fixes or pointing out where problems are in the code's XML if I can determine.

**Any special expertise you think is good to know**
I can contribute my UI opinion, a functional perspective and my graphic design skills if necessary.

Thanks for all your work.

**Comment by jeroenpardon** [comment]
Hi folks, welcome :)

I will be away or busy the coming days, so I don't have a whole lot of time but I just wanted to say thanks for showing an interest in Grid ! When I get the time I will respond to some of the things you wrote and hopefully provide you with some more insight about Grid

Cheers,
Jeroen

**Comment by jeroenpardon** [comment]
@Donderstraal Navigation is definitely important and something I pay a lot of attention to in Grid. What makes a homescreen good is very personal I have found over the years. There's always something wrong with it for someone ;) 

There will be two or three homescreens in Grid eventually, probably two at launch.

By default the _Minimal_ layout is selected, a vertical menu focused on speed and readability but also showcasing the fanart from your collection. Functionality wise this one is similar to the one currently in reFocus.

The _Stream_ layout is focused on at a glance information provided by widgets. Think of this as a newsfeed of library sections or dynamic playlists. The home menu is icon based, does not use submenus. This layout really puts the widgets center stage.

There will probably be a horizontal layout too eventually, but probably not on launch.

About widgets. Something I always hated about traditional widget implementations is that there's not many useful widget options available for most menu entries. Sure, for movies, tv shows and music you can show things like recently added. But basically anything else doesn't have useful info. So then people either have an "empty" spot or just put stuff in there to "fill the gaps".

So, in Grid I opted for a single "stream" of widgets. That stream is a group of widgets always available by pressing right on the main menu and shows the same widgets regardless on what menu item is focused. You can choose from several layout options for each widget.

About the colours, Grid is relatively dark by default (not pitch black or anything like that), but the colours will also be completely customizable. You can set the colours through a colorpicker interface. It comes with a pretty extensive palette, but you can also set the colours manually using HEX.

**Comment by jeroenpardon** [comment]
@loggio I know about being picky, it's pretty much the reason I started skinning ;)

Regarding viewtypes, one thing I try to do is to really tailor them to the content being displayed. I hate "unisex" views where space is wasted because other art types need to occupy the same space, if you know what I mean.

Originally my intention was even to have just one viewtype. I have expanded on that a bit, but there's just never going to a huge number of viewtypes.

Looks like we have the PVR part covered then, my favourite part :-P Joking aside, I really want the PVR to work well, but with regards to user interation Kodi's implementation is still a mess of inconsistencies afaic :)

Regarding Github, you can take it as far as you want to. It's primarily a matter of posting issues you come across. I'm not expecting you to make pull requests and stuff like that, although you can if you want to of course.

**Comment by jeroenpardon** [comment]
@bigdaddyral Sounds like you'll fit right in :) Any place I could check out your film projects ?
The trailer sounds cool, do you travel around for film making ?
Cool to have you on board, hopefully Grid will find a place ther too :)

**Comment by jeroenpardon** [comment]
@purpleman2k I agree about the over the top designs. Personal preferences I guess, but to me good design is about knowing what to leave out more than how much you can put in.

Hopefully I can keep the bug reports needed to a minimum ;)

**Comment by monkeyboyohyeah** [comment]
**Why do you want to test Grid?**
I've used ReFocus for many years, and now it's been deprecated (is that the word?) I can't find another skin I like... and I think I've tried them all. So keen to get into Grid and triple keen to help out in any way I can.

**What do you use Kodi for mostly?**
Daily Movies/TV/Streaming + Music (HiFiBerry Dac+) to Amplifier on multiple R-Pis with OSMC using mySQL database on NAS.

**What do you look for in a Kodi skin?**
Design, UX, customisability, simplicity. I find a lot of skins are counterintuitive to use and most are downright ugly.

**What would you be able to contribute to best?**
I'm a graphic designer, although I think you've probably got that covered – either yourself, or someone else on this board (nice Grid logo BTW). I'm offering to submit regular feedback on bugs/UX, etc.

**Any special expertise you think is good to know**
If something doesn't work intuitively I'll let you know. I'm a stickler for detail, and personally highly motivated to have this skin polished.

Thanks for all your work on ReFocus.

**Comment by jeroenpardon** [comment]
@monkeyboyohyeah welcome! It's shaping up to be a nice team :)
I definitely look forward to your (and others) feedback on the music section as I don't really use it a whole lot. That said, the music library and Kodi's music specific skinning engine features are definitely too limited to get it up to a standard I would like to see.

I hope to strike a good balance between customisability and simplicity. I definitely don't want dozens of checkboxes all over the place, but I do want to offer some good options.

Yeah, the skin design and coding go hand in hand afaic. I'm a designer by heart and I wanted to learn to make my ideas become reality by learning the coding side of things. 

Of course I am open to any suggestions, but I wouldn't be developing skins if I wouldn't be able to design them :)

Glad you like the logo, I'm not completely sure about it. I have some other ideas lying around but for now this is the choice.

**Comment by jeroenpardon** [comment]
So, unless I run into serious issues I think a first beta will be ready in 2 weeks, possibly 1 week.

**Comment by KOKONUTCREME** [comment]
Hi Jeroen

•Why do you want to test Grid?
To be an active participant and team contributor to the success of your skin.  reFocus has a point of difference to other skins with its layout, font type and viewtypes.  I'm curious and interested in seeing what direction you're taking with Grid.  The name also has me intrigued in what to expect.

•What do you use Kodi for mostly?
Mainly streaming local video content via SMB shares from my Mac to Windows laptop connected to TV - movies and tv shows.  I don't use Kodi a lot for listening to music and haven't installed a PVR for live TV content.  I use some third party addons for online content - mainly YouTube, Trailers and TED Talks.

•What do you look for in a Kodi skin?
Smooth and fast navigation is my first preference.  When your movie library expands beyond 1000 you begin to appreciate navigation speed more and eye candy less.  When I look at commercial products like Amazon, Netflix, Apple etc the UI layout is clean and uncluttered by lots of technical data or additional artwork.  Compared to some KODI skins, it's a very minimalist approach but when all you want to do is find something to watch, getting fixated on features or information that doesn't really add value to your viewing experience matters to me.

•What would you be able to contribute to best?
Bug reports, fixes, suggestions.

**Comment by jeroenpardon** [comment]
Welcome @KOKONUTCREME 
About the name, it does say a bit about the looks of the design, but mainly it refers to a methodology of the design process. It's something I sort of brought over from my web development. Basically, everything is laid out based on a grid system as to ensure a level of consistency.

I agree on your comments about providing keeping perspective on the usability. To me, design is as much (if not more) about choosing what not to add than choosing what to add. I could make an "everything but the kitchen sink" skin and stick anything there is into any leftover space, no problem :) Instead I would much rather think twice, thrice or more about whether or not it really adds value.

In the end I hope to find that balance where looking good and functionality are in harmony :)

I'll get off my soapbox now, beta release not far away :)

**Comment by bigdaddyral** [comment]
@jeroenpardon Thank you, sir. I don't have anything online currently but am working on something for later this year. Right now I'm awaiting a Pansonic GH5 that I can put to work. I haven't taken the Airstream around yet for film making purposes, but certainly hope to. I'm working out the logistics of a Route 66 road trip right now, but I wouldn't be kicking that off until later in the year as well. I appreciate the chance to help out and can't imagine Grid won't become my new standard. Very few have the minimalist design aesthetic you do that speaks to me as well. Looking forward to putting the first beta through it's paces!

**Comment by FrissonReynald** [comment]
Hi all 

    Why do you want to test Grid?

I would like to try your new skin in beta to continue my learning coding. And above all because I am a fervent admirer of your work for a very long time. A new skin is wonderful to welcome.
    **What do you use Kodi for mostly?**
I use kodi to watch movies and TV series mainly.
    **What do you look for in a Kodi skin?**
What I'm looking for in a new skin is simplicity, very lightweight and simple and effective views. I'm waiting for this new skin to be opened on the big screen, with quick possibility of changing font size and background color. I do not want any more gas plants that are too complicated to parameterize.
    **What would you be able to contribute to best?**
I watch a lot of movies and family alike. All the devices could use new skin to you. My Kodi is 24 / 24h connected and I can see where the navigation problems will be.
    **Any special expertise you think is good to know
Everything is used to who knows how to use it.
    Etc.**

Just tell me what you think and how you can help. There's no good or wrong here, I'll be looking for people with different backgrounds. Motivations, contributions.

Personally I do not pretend to be better than others for Grid Beta tester, but my approach to coding on refocus at the time and then my creations of skin (amateur) make me someone who will have a look More demanding and artistic. I'm a keen on using KODI as I said. I am a musician and creator and it is an exciting adventure to see a new skin live. My great motivation is sharing and discovery. And if it comes from you Jeroen, well I'm happy ^^.
Here, I hope I will be part of this new adventure

**Comment by jeroenpardon** [comment]
@FrissonReynald Welcome back Reynald :)

@Donderstraal @loggio @bigdaddyral @purpleman2k @monkeyboyohyeah @Slurrrp I think I am about to close this as I think we have gathered a good team.

I expect to upload the first commit of Grid some time this week. Before doing that I will be sending you all invites to the private repository. That way I can give you some more information about the testing and we'll be able to check if everything is working as it should (first time I will be using a private repository).

Cheers,
Jeroen

**Comment by jeroenpardon** [comment]
Invites have been sent. As said, the skin is not available just yet, but if you could all confirm the invitations we'll be set to go for later. 

Once you have accepted the invitation, please check [this link](https://github.com/jeroenpardon/skin.grid/issues/3) when you have the time.

Cheers,
Jeroen

**Comment by KOKONUTCREME** [comment]
Hi Jeroen

Just wanting to confirm that I've not been invited or that I was missed from the list?

Thanks

**Comment by jeroenpardon** [comment]
@KOKONUTCREME Sorry about that, totally unintended. Invite incoming

**Comment by slack8182** [comment]
Why do you want to test Grid?
I feel like I've downloaded and tried almost every kodi skin made and I always go back to refocus. So I know I'll enjoy it
What do you use Kodi for mostly?
For keeping my movies and tvshows collection organized. 
What do you look for in a kodi skin?
Something that is readable from a TV. Clean and crisp. 
What would you be able to contribute? 
I've been a kodi user since Gotham and have tried almost every skin whether it's a full release or just an alpha or beta. I think I could give good insight on what most users who use kodi on their TV are looking for.

**Comment by jeroenpardon** [comment]
Hi, sorry but for now signups are closed.
